# -*- coding: utf-8 -*-
"""Task1: Variables and Operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1737YRYWHgRAhQe9VbqZ1e2PVIb02pRiP

Answer each question by doing some operations with Python. Put conclusion in the comments

1.1 For the following variables, use the function type() from Python to check the data type for the variables.
"""

x1 = 1.1
x2 = "Monday"
x3 = "1.1"
x4 = True
x5 = "True"
x6 = -1

"""1.2 What is the difference between variables x1 and x3?"""

# type(x1)



"""1.3 What happens if you subtract x3 from x1?"""



"""1.4 What is the difference between variables x4 and x5?"""





"""1.5 What happens if you subtract x5 from x4?"""



"""2.1 To gather input from the user, we can use the function input(message), where “message” is a meaningful message of type str and will be displayed to the user."""



"""Question 1: Print the values of the two variables? As you might have noticed, data type of x1 and x2 is string. Even though we entered integers, the input function converts them into string by default. Now we do some data type conversion from string to integers:"""



"""Question 2: What is the data type of x1 and x2? Now perform simple comparisons between x1 and x2:

Check if the two variables are equal?

Check if x1 is greater than x2?

Check if x2 is greater than x1?

Check if x1 is not equal to x2?

Store the difference between the two variables x1 and x2 in another variable x3 (subtract the smaller number from the larger number).

Increment the smaller of the two variables (x1 and x2) with the difference.Use the shorthand addition operator for the same. Again check if x1 and x2 are equal or not?
"""















